version: '3'

volumes:
  api: { }
  postgres: { }
  postgres_backups: { }
  data01:
    driver: local

services:

  app:
    build:
      context: .
      dockerfile: ./compose/local/api/DockerFile
    container_name: go-gin-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - ./.env
    volumes:
      - .:/app
    restart: always


  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    container_name: postgres
    image: local_postgres
    volumes:
      - postgres:/var/lib/postgresql/data:delegated
      - postgres_backups:/backups:delegated
    env_file:
      - ./.env
    ports:
      - "5432:5432"